version: '3.9'
name: 'sensors-lab'

services:
  ros-docker:
    image: test/docker_image 
    entrypoint: ["/bin/bash", "-ci", "source /opt/ros/noetic/setup.bash && cd /ros_ws && catkin build && source /ros_ws/devel/setup.bash && roslaunch sensors_lab solution.launch"]
    container_name: ros_noetic_container
    stdin_open: true
    tty: true
    environment:
      - DISPLAY
      - XAUTORITY
      - QT_X11_NO_MITSHM=1
      - GUI=true
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - ./:/ros_ws/src/solution
  